# Minecraft & Fabric Versions
minecraft_version=1.19.4
yarn_mappings=1.19.4+build.2
loader_version=0.14.25

# Fabric API
fabric_version=0.87.0+1.19.4

# Mod Properties
mod_version=0.1.0-alpha
maven_group=com.blockscope
archives_base_name=blockscope

# Java
org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Java/jdk-17