#Blockscope Configuration
#Sun May 03 17:10:43 EDT 2026
resolution_height=360
entity_capture_radius=16
aspect_ratio_mode=preserve
resolution_width=640
capture_block_entities=true
show_chat_messages=true
capture_all_entities=true
capture_nearby_blocks=true
recording_directory=./recordings
capture_nearby_entities=true
block_capture_radius=128
show_recording_overlay=true
use_relative_block_positions=false
server_url=http\://localhost\:9000
ffmpeg_path=/opt/homebrew/bin/ffmpeg
target_fps=20
capture_item_entities=true
